#!/usr/bin/env bash
# Measures how long the app image takes to become ready in a container sized like a free web instance
# (0.1 CPU, 512 MB), with and without the JDK AOT cache and C1-only JIT. Writes docs/coldstart.md.
#
# Usage: make coldstart   (needs Docker and Python 3; takes 20-30 minutes because the slow variant is slow)
#
# "Ready" = time from `docker run` until /actuator/health/readiness reports UP, against an already migrated
# PostgreSQL, so it covers JVM start, Spring context and the readiness probe. The container limit is a CFS quota
# on this machine's CPU; a hosting provider's 0.1 CPU runs on different hardware.
set -euo pipefail
cd "$(dirname "$0")/.."

IMAGE=market-data-app:coldstart
NET=market-data-coldstart
DB=market-data-coldstart-db
APP=market-data-coldstart-app
RUNS=${RUNS:-2}
LIMITS=(--cpus=0.1 --memory=512m)
BASE_OPTS="-XX:MaxRAMPercentage=70 -XX:+UseSerialGC -Xss512k"
OUT=docs/coldstart.md
RESULTS=$(mktemp)

cleanup() {
  docker rm -f "$APP" "$DB" >/dev/null 2>&1 || true
  docker network rm "$NET" >/dev/null 2>&1 || true
  rm -f "$RESULTS"
}
trap cleanup EXIT

now() { python3 -c 'import time; print(time.time())'; }

# run_once LABEL JAVA_OPTS [docker limits...] -> appends "label|ready seconds|started seconds" to RESULTS
run_once() {
  local label="$1" opts="$2"; shift 2
  docker rm -f "$APP" >/dev/null 2>&1 || true
  local t0; t0=$(now)
  docker run -d --name "$APP" --network "$NET" -p 18383:8080 "$@" \
    -e SPRING_DATASOURCE_URL="jdbc:postgresql://$DB:5432/marketdata" \
    -e SPRING_DATASOURCE_USERNAME=marketdata -e SPRING_DATASOURCE_PASSWORD=marketdata \
    -e DEMO_SEED=never -e INGEST_SCHEDULE_ENABLED=false -e DB_POOL_SIZE=3 \
    -e JAVA_TOOL_OPTIONS="$opts" "$IMAGE" >/dev/null
  for _ in $(seq 1 1800); do
    if curl -fs http://localhost:18383/actuator/health/readiness 2>/dev/null | grep -q UP; then
      local t1; t1=$(now)
      local started; started=$(docker logs "$APP" 2>&1 | grep -o 'Started MarketDataApplication in [0-9.]*' | grep -o '[0-9.]*$')
      local ready; ready=$(python3 -c "print(round($t1 - $t0, 1))")
      echo "$label|$ready|$started" >> "$RESULTS"
      echo "  $label: ready after ${ready} s (Spring: started in ${started} s)"
      return 0
    fi
    sleep 0.5
  done
  echo "$label|>900|" >> "$RESULTS"
  echo "  $label: not ready after 900 s"
}

echo "Building $IMAGE ..."
docker build -q -t "$IMAGE" . >/dev/null
docker network create "$NET" >/dev/null
docker run -d --name "$DB" --network "$NET" -e POSTGRES_DB=marketdata -e POSTGRES_USER=marketdata \
  -e POSTGRES_PASSWORD=marketdata postgres:18-alpine >/dev/null
until docker exec "$DB" psql -U marketdata -d marketdata -c 'SELECT 1' >/dev/null 2>&1; do sleep 1; done

echo "Applying migrations with one unconstrained start (not reported) ..."
run_once "warm-up" "$BASE_OPTS" >/dev/null
: > "$RESULTS"

echo "Unconstrained reference:"
run_once "Unconstrained, AOT cache" "$BASE_OPTS"
run_once "Unconstrained, no AOT cache" "$BASE_OPTS -XX:AOTMode=off"

echo "0.1 CPU / 512 MB:"
for i in $(seq 1 "$RUNS"); do
  run_once "AOT cache + C1 only (deploy/render.yaml)" "$BASE_OPTS -XX:TieredStopAtLevel=1" "${LIMITS[@]}"
  run_once "AOT cache, default JIT" "$BASE_OPTS" "${LIMITS[@]}"
  run_once "No AOT cache, C1 only" "$BASE_OPTS -XX:AOTMode=off -XX:TieredStopAtLevel=1" "${LIMITS[@]}"
  run_once "No AOT cache, default JIT" "$BASE_OPTS -XX:AOTMode=off" "${LIMITS[@]}"
done

python3 - "$RESULTS" "$OUT" "$RUNS" <<'PY'
import datetime as dt, platform, subprocess, sys
from collections import OrderedDict
results_path, out_path, runs = sys.argv[1], sys.argv[2], int(sys.argv[3])

def sh(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"

mem = sh(["sysctl", "-n", "hw.memsize"])
docker = sh(["docker", "info", "--format", "{{.NCPU}}|{{.MemTotal}}"]).split("|")
rows = OrderedDict()
for line in open(results_path):
    label, ready, started = line.strip().split("|")
    rows.setdefault(label, []).append((ready, started))
lines = [
    "# Cold start",
    "",
    "Generated by `make coldstart` (`scripts/coldstart.sh`). **Local run:** the app image in a container limited "
    "to 0.1 CPU and 512 MB (Docker CFS quota) on a laptop, against an already migrated PostgreSQL 18 with no "
    "demo seeding. A hosting provider's 0.1 CPU is different hardware, so treat these as relative numbers.",
    "",
    f"- Date: {dt.date.today().isoformat()}",
    f"- Machine: {sh(['sysctl', '-n', 'machdep.cpu.brand_string'])}, "
    f"{int(mem) / 2**30:.0f} GiB RAM, macOS {sh(['sw_vers', '-productVersion'])}; "
    f"Docker VM: {docker[0]} CPUs, {int(docker[1]) / 2**30:.1f} GiB" if mem.isdigit() and len(docker) == 2
    else f"- Machine: {platform.platform()}",
    "- JVM flags in every run: `-XX:MaxRAMPercentage=70 -XX:+UseSerialGC -Xss512k` (as in deploy/render.yaml), "
    "plus the variant's flags. The image always ships the AOT cache; `-XX:AOTMode=off` disables it.",
    "- Ready = from `docker run` until `/actuator/health/readiness` is UP. Spring = the "
    "\"Started MarketDataApplication in N seconds\" log line.",
    "",
    "| Variant | " + " | ".join(f"Run {i + 1}: ready (Spring)" for i in range(runs)) + " |",
    "|---|" + "---:|" * runs,
]
for label, values in rows.items():
    cells = [f"{r} s ({s} s)" if s else f"{r} s" for r, s in values]
    cells += [""] * (runs - len(cells))
    lines.append(f"| {label} | " + " | ".join(cells) + " |")
lines.append("")
open(out_path, "w").write("\n".join(lines))
PY
echo "Wrote $OUT"
