#!/usr/bin/env python3
"""Turns the k6 summary written by loadtest/k6.js into docs/loadtest.md (called by scripts/loadtest.sh)."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import platform
import re
import statistics
import subprocess
from pathlib import Path

# Must match the scenarios in loadtest/k6.js (start offset and duration in seconds).
SCENARIOS = {
    "steady": {"start": 25, "duration": 60, "label": "Steady: 200 requests/s (open model)"},
    "saturation": {"start": 90, "duration": 60, "label": "Saturation: 32 clients, no think time (closed model)"},
}
ENDPOINTS = ["bars", "indicators", "levels", "symbols"]


def sh(cmd: list[str]) -> str:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def machine() -> dict[str, str]:
    mem = sh(["sysctl", "-n", "hw.memsize"])
    docker = sh(["docker", "info", "--format", "{{.NCPU}}|{{.MemTotal}}"]).split("|")
    return {
        "cpu": sh(["sysctl", "-n", "machdep.cpu.brand_string"]),
        "memory": f"{int(mem) / 2**30:.0f} GiB" if mem.isdigit() else mem,
        "os": f"macOS {sh(['sw_vers', '-productVersion'])}" if platform.system() == "Darwin" else platform.platform(),
        "docker": f"{docker[0]} CPUs, {int(docker[1]) / 2**30:.1f} GiB" if len(docker) == 2 else "unknown",
    }


def cpu_averages(stats_path: Path, k6_start: int) -> dict[str, dict[str, float]]:
    """Mean container CPU% per scenario, skipping the first and last 5 s of each phase."""
    samples: list[tuple[int, str, float]] = []
    for line in stats_path.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[2].endswith("%"):
            samples.append((int(parts[0]), parts[1], float(parts[2].rstrip("%"))))
    result: dict[str, dict[str, float]] = {}
    for name, sc in SCENARIOS.items():
        lo, hi = k6_start + sc["start"] + 5, k6_start + sc["start"] + sc["duration"] - 5
        for container in ("app", "db"):
            values = [cpu for t, n, cpu in samples if lo <= t <= hi and n.endswith(f"-{container}-1")]
            if values:
                result.setdefault(name, {})[container] = statistics.mean(values)
    return result


def ms(value: float) -> str:
    return f"{value:.1f} ms" if value >= 10 else f"{value:.2f} ms"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", required=True)
    parser.add_argument("--dataset", required=True, help="symbols|bars|heap size|server version")
    parser.add_argument("--k6-version", required=True)
    parser.add_argument("--k6-exit", required=True)
    parser.add_argument("--stats", required=True)
    parser.add_argument("--k6-start", required=True, type=int)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    metrics = json.loads(Path(args.summary).read_text())["metrics"]
    symbols, bars, heap, pg_version = args.dataset.split("|")
    host = machine()
    cpu = cpu_averages(Path(args.stats), args.k6_start)
    k6_version = re.sub(r"\s*\(.*\)", "", args.k6_version)

    def values(name: str) -> dict[str, float]:
        return metrics[name]["values"]

    lines = [
        "# Load test",
        "",
        "Generated by `make loadtest` (`scripts/loadtest.sh`, `loadtest/k6.js`). **Local run on synthetic data:** "
        "k6 and the docker compose stack ran on the same laptop, so these numbers describe this machine, not a "
        "deployment.",
        "",
        f"- Date: {dt.date.today().isoformat()}",
        f"- Machine: {host['cpu']}, {host['memory']} RAM, {host['os']}; Docker VM: {host['docker']}",
        "- Containers: app limited to 2 CPUs / 1 GB (Temurin 25 JRE, `-XX:MaxRAMPercentage=75`, virtual threads, "
        f"Hikari pool 10); PostgreSQL {pg_version} limited to 2 CPUs / 2 GB, default settings",
        f"- Dataset: {int(symbols):,} synthetic symbols, {int(bars):,} daily bars (bars heap {heap}), generated by the "
        "demo seeder",
        "- Client: " + k6_version + ", requests with `Accept-Encoding: gzip`; per-IP rate limiting disabled "
        "(`RATE_LIMIT_ENABLED=false`) because every request comes from one IP",
        "- Mix per request: 40% `/v1/bars/{ticker}` (1 year, up to 1000 rows), 30% `/v1/indicators/{ticker}` "
        "(1 year), 20% `/v1/levels/{ticker}`, 10% `/v1/symbols?q=` (prefix search); random ticker each time",
        "- A 20 s warm-up at 100 requests/s runs first and is not reported",
        "",
        "## Results",
        "",
        "| Scenario | Requests | Throughput | p50 | p95 | p99 | Max | Errors | App CPU | DB CPU |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for name, sc in SCENARIOS.items():
        d = values(f"http_req_duration{{scenario:{name}}}")
        count = values(f"http_reqs{{scenario:{name}}}")["count"]
        failed = values(f"http_req_failed{{scenario:{name}}}")["rate"]
        c = cpu.get(name, {})
        lines.append(
            f"| {sc['label']} | {count:,} | {count / sc['duration']:.0f} req/s | {ms(d['med'])} | {ms(d['p(95)'])} | "
            f"{ms(d['p(99)'])} | {ms(d['max'])} | {failed:.2%} | "
            f"{c.get('app', float('nan')):.0f}% | {c.get('db', float('nan')):.0f}% |")
    dropped = values("dropped_iterations{scenario:steady}")["count"]
    lines += [
        "",
        f"Throughput is requests divided by the 60 s scenario. The steady scenario dropped {dropped:.0f} iterations "
        "(k6 drops one when it cannot start a request on time). CPU columns are the mean of `docker stats` samples "
        "every few seconds during each scenario; 100% = one CPU, so each container's ceiling is 200%.",
        "",
        "## Latency by endpoint",
        "",
        "| Endpoint | Steady p50 | Steady p95 | Saturation p50 | Saturation p95 |",
        "|---|---:|---:|---:|---:|",
    ]
    for endpoint in ENDPOINTS:
        s = values(f"http_req_duration{{scenario:steady,endpoint:{endpoint}}}")
        t = values(f"http_req_duration{{scenario:saturation,endpoint:{endpoint}}}")
        lines.append(f"| `{endpoint}` | {ms(s['med'])} | {ms(s['p(95)'])} | {ms(t['med'])} | {ms(t['p(95)'])} |")
    lines += [
        "",
        f"k6 exit code: {args.k6_exit} (0 = all thresholds in `loadtest/k6.js` passed).",
        "",
    ]
    Path(args.out).write_text("\n".join(lines))


if __name__ == "__main__":
    main()
